'use client'
import { useEffect, useState } from 'react'
import { supabaseBrowser } from '@/lib/supabase'
import RichTextEditor from '@/app/components/rich-text-editor'

type Item = { id:string; title:string; destination:string; price:string; status:string; description:string; image_url:string|null }
const empty = { title:'', destination:'', price:'', status:'draft', description:'', image_url:'' }

export default function Tours(){
  const [items,setItems]=useState<Item[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const supabase=supabaseBrowser()
  async function load(){const {data}=await supabase.from('tours').select('*').order('created_at',{ascending:false});setItems(data||[])} useEffect(()=>{load()},[])
  function edit(x:Item){setEditing(x.id);setForm({title:x.title,destination:x.destination,price:x.price||'',status:x.status,description:x.description||'',image_url:x.image_url||''});setFile(null);window.scrollTo({top:0,behavior:'smooth'})}
  function reset(){setEditing(null);setForm(empty);setFile(null);setMessage('')}
  async function uploadImage(){if(!file)return form.image_url;const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`tours/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('media').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabase.storage.from('media').getPublicUrl(path).data.publicUrl}
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const image_url=await uploadImage();const payload={...form,image_url};const result=editing?await supabase.from('tours').update(payload).eq('id',editing):await supabase.from('tours').insert(payload);if(result.error)throw result.error;setMessage(editing?'Đã cập nhật tour.':'Đã thêm tour.');reset();await load()}catch(err:any){setMessage(err?.message||'Có lỗi xảy ra.')}finally{setBusy(false)}}
  async function remove(id:string){if(!confirm('Xóa tour này?'))return;const {error}=await supabase.from('tours').delete().eq('id',id);if(error)setMessage(error.message);else load()}
  return <main className="container" style={{padding:'45px 22px'}}><div style={{display:'flex',justifyContent:'space-between',gap:15,alignItems:'center',flexWrap:'wrap'}}><div><h1>{editing?'Sửa tour':'Quản lý tour'}</h1><p style={{color:'#66736b'}}>CRUD đầy đủ + hình ảnh.</p></div>{editing&&<button className="btn" onClick={reset}>Hủy sửa</button>}</div><form className="card" onSubmit={save} style={{padding:22,display:'grid',gap:12,margin:'25px 0'}}><input className="input" placeholder="Tên tour" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><input className="input" placeholder="Điểm đến" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} required/><input className="input" placeholder="Giá" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Nháp</option><option value="published">Công khai</option></select><div><label className="editor-label">Mô tả tour</label><RichTextEditor key={editing||'new'} value={form.description} onChange={description=>setForm({...form,description})} placeholder="Mô tả lịch trình, điểm nổi bật, dịch vụ..."/></div><input className="input" type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/>{form.image_url&&<img src={form.image_url} alt="Ảnh hiện tại" style={{width:180,height:110,objectFit:'cover',borderRadius:12}}/>}<button className="btn btn-primary" disabled={busy}>{busy?'Đang lưu...':editing?'Lưu thay đổi':' + Thêm tour'}</button>{message&&<p>{message}</p>}</form><div className="grid-auto">{items.map(x=><div className="card" style={{padding:20}} key={x.id}>{x.image_url&&<img src={x.image_url} alt="" style={{width:'100%',height:150,objectFit:'cover',borderRadius:12,marginBottom:12}}/>}<b>{x.title}</b><p>{x.destination}</p><small>{x.status} · {x.price||'Chưa có giá'}</small><div style={{display:'flex',gap:8,marginTop:12}}><button className="btn" onClick={()=>edit(x)}>Sửa</button><button className="btn" onClick={()=>remove(x.id)}>Xóa</button></div></div>)}</div></main>
}
