'use client'
import {useEffect,useState} from 'react'
import {supabaseBrowser} from '@/lib/supabase'

type Category={id:string;name:string;slug:string;description:string|null;image_url:string|null;status:string}
const empty={name:'',slug:'',description:'',image_url:'',status:'published'}
export default function Categories(){
 const s=supabaseBrowser(); const [items,setItems]=useState<Category[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
 async function load(){const {data}=await s.from('project_categories').select('*').order('created_at',{ascending:false});setItems(data||[])} useEffect(()=>{load()},[])
 function reset(){setEditing(null);setForm(empty);setMessage('')}
 function edit(x:Category){setEditing(x.id);setForm({name:x.name,slug:x.slug,description:x.description||'',image_url:x.image_url||'',status:x.status});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');const payload={...form,slug:form.slug.trim().toLowerCase().replace(/\s+/g,'-')};const r=editing?await s.from('project_categories').update(payload).eq('id',editing):await s.from('project_categories').insert(payload);if(r.error)setMessage(r.error.message);else{setMessage(editing?'Đã cập nhật danh mục.':'Đã tạo danh mục.');reset();load()}setBusy(false)}
 async function remove(id:string){if(!confirm('Xóa danh mục? Dự án bên trong sẽ không bị xóa nhưng sẽ bỏ liên kết danh mục.'))return;const {error}=await s.from('project_categories').delete().eq('id',id);if(error)setMessage(error.message);else load()}
 return <main className="container section"><div className="admin-top"><div><div className="eyebrow">PROJECT CATEGORIES</div><h1>Danh mục dự án</h1><p>Gom nhiều dự án theo khu vực, dòng sản phẩm hoặc chiến dịch.</p></div><a className="btn" href="/admin">← Dashboard</a></div><form className="card form-grid" onSubmit={save}><input className="input" placeholder="Tên danh mục *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="input" placeholder="Slug, ví dụ: bao-loc" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} required/><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="published">Công khai</option><option value="draft">Nháp</option><option value="archived">Lưu trữ</option></select><input className="input" placeholder="Mô tả ngắn" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="full actions-row"><button className="btn btn-primary" disabled={busy}>{busy?'Đang lưu...':editing?'Lưu thay đổi':'Tạo danh mục'}</button>{editing&&<button type="button" className="btn" onClick={reset}>Hủy</button>}</div>{message&&<div className="full success">{message}</div>}</form><div className="grid-auto">{items.map(x=><article className="card admin-project" key={x.id}><div className="placeholder">DANH MỤC</div><div><div className="eyebrow">{x.status}</div><h3>{x.name}</h3><p>{x.description||'Chưa có mô tả'}</p><div className="actions-row"><a className="btn btn-primary" href={`/admin/projects?category=${x.id}`}>Xem dự án</a><button className="btn" onClick={()=>edit(x)}>Sửa</button><button className="btn" onClick={()=>remove(x.id)}>Xóa</button></div></div></article>)}</div></main>
}
